<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuites01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c305f9d3-0a08-4c8e-9016-472218fb99c4</testSuiteGuid>
   <testCaseLink>
      <guid>bc448c13-34bc-4fe5-9c7d-2dd20fdfaea9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase05</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1849c73-f70f-4543-8bd9-8a4272ac1900</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>388e8760-c40d-4f26-a2df-3cbb8780312e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdce7feb-b75c-46ab-bfd6-cbdb22bd63f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4bf7805-d223-4f10-8751-16da28676715</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase04</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>071fa7b4-242b-4204-bd28-732458e74783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e22c0f3d-ea84-4389-8a6b-ab649031bb51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b373ae7-f85d-42fc-bcaf-9374b046484c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e74d200e-97b0-422b-84cc-feafe1b84612</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase03</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eb1b52c-555a-472b-96b2-bf24e197ddb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd29fac8-74d7-464c-b9e0-998e4a69ff7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3e07011-8a06-42b2-9f2c-8aa7836c714c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c99cd69-a5cf-4071-81b5-f63867a11c03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase02</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>794b0096-d8af-4ed9-822c-3f1138e8cf05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c98544ec-efe7-4744-a766-93afd0df7ac4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6e17b82-e69f-4435-970b-d0c715035019</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>674a49a0-aaf2-4379-9fe2-762fa22aa15b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6279d86b-6521-4b32-819f-cf58da7815d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d47819-2020-415d-a7a5-0e45009ca8d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a10eac27-0995-469b-913a-fb9da8c43e4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
